version: "3.8"

services:
  reservation-mongo-db:
    container_name: "reservation-mongo-db"
    image: mongo:6.0
    restart: on-failure
    ports:
      - ${DB_PORT}:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
      - MONGO_INITDB_DATABASE=${DB_NAME}
    volumes:
      - reservation-mongo-db-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
volumes:
  reservation-mongo-db-data:
    driver: local
networks:
  default:
    driver: bridge
